### ISSUE TITLE
get question list issue

### ISSUE THREAD

**Issue by omh02033** [2022-dimipay-recruit/WEB-Backend#16]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/59903612/173956894-e1b14e06-db87-4414-8238-1ad10b29fbe5.png">

응답은 잘 오는데 백엔드에 오류 로그만 나타납니다

<img width="750" alt="image" src="https://user-images.githubusercontent.com/59903612/173956754-7f121a50-0dc9-49d0-b280-ccf69e59450f.png">

**Comment by kraccoon-dev** [comment]
확인해보겠습니다

**Comment by kraccoon-dev** [comment]
그리고 문서에서 run in postman 누르면 제가 미리 작성한 요청들 써보실 수 있어요👀
