### ISSUE TITLE
user find issue

### ISSUE THREAD

**Issue by omh02033** [2022-dimipay-recruit/WEB-Backend#23]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/59903612/174017561-160d5a60-fa13-400e-a263-4f5623349612.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/59903612/174017608-84e16ece-094d-41fd-a6b7-00db0f451462.png">

유저 검색 이슈 있습니다.

**Comment by kraccoon-dev** [comment]
쿼리를 `keyword=~`로 변경하고 다시 해보시겠어요?
