### ISSUE TITLE
feed issue

### ISSUE THREAD

**Issue by omh02033** [2022-dimipay-recruit/WEB-Backend#43]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/59903612/174467729-f0caf6ac-6cee-47e3-aea4-d21e97a02f7c.png">
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/59903612/174467747-87646e8e-c8c0-4bcf-a04d-ffaa11980a6a.png">

값이 오지 않습니다

**Comment by kraccoon-dev** [comment]
팔로우 되어있나요?

**Comment by omh02033** [comment]
> 팔로우 되어있나요?

넵
audgns23 계정이 omh0203 계정을 팔로우 한 상태입니다.

**Comment by omh02033** [comment]
랜덤 피드도 넘어오지 않습니다

**Comment by kraccoon-dev** [comment]
답변일이 오늘이 아니라서 그런것 같습니다. 답변을 불러오는 기준을 3일 전부터로 설정할까요?

**Comment by omh02033** [comment]
네네 그렇게 해주세요

received는 왜 배열로 오나요..?

**Comment by kraccoon-dev** [comment]
팔로우한 사용자에게서 여러개의 답변을 받을 수 있기때문입니다.

**Comment by omh02033** [comment]
한 질문에 여러개의 답변을 받을 수 있다는건가요..?

**Comment by kraccoon-dev** [comment]
팔로우한 사람의 피드가 여러개가 있을 수 있다는 뜻이었습니다.
a가 b를 팔로우하 하고 있을 때 b가 두 개의 답변을 하면 이 둘이 배열로 들어옵니다.

**Comment by omh02033** [comment]
아 이해했습니다~!

**Comment by omh02033** [comment]
팔로우 했을 때, 팔로우피드와 랜덤피드가 같은질문이 동시에 나옵니다.
해결가능할까요?

**Comment by kraccoon-dev** [comment]
넵
