### ISSUE TITLE
prisma version issue

### ISSUE THREAD

**Issue by omh02033** [2022-dimipay-recruit/WEB-Backend#7]
`error: server error {"data":{"clientVersion":"3.14.0"},"timestamp":"2022-06-13 18:40:10"}`

서버에 요청을 보내면 이런 에러가 반환됩니다.
![image](https://user-images.githubusercontent.com/59903612/173333600-bc8c5ac5-3e45-455f-a130-b67e6d01dfba.png)
<img width="749" alt="image" src="https://user-images.githubusercontent.com/59903612/173333765-d805b189-135a-4043-8c79-a94a767dcb5f.png">

prisma/client version : `3.14.0`

**Comment by kraccoon-dev** [comment]
혹시 `prisma db push` 해보셨나요?

**Comment by omh02033** [comment]
해결했습니다 !
